### ISSUE TITLE
Gallery! ?

### ISSUE THREAD

**Issue by maka-io** [jaydenseric/apollo-upload-server#10]
In the multipart example, could you provide and example type for "Gallery"?

Thanks!

**Comment by jaydenseric** [comment]
I'm not sure how you mean the question, it is just a made up example so `Gallery` could have anything in it. Were you asking for a recommended way to setup a gallery?

**Comment by jaydenseric** [comment]
Closing, but feel free to continue the conversation.

**Comment by maka-io** [comment]
Thanks, since it was made up I was wondering if you had an idea of a made up Gallery type for the sake of example completeness.  Soup to nuts sort of thing.
```
    type Gallery {
        id: Int
        // whatever: 'else'
    }
```

**Comment by jaydenseric** [comment]
Agreed, while having a more "real-world" example can be useful it introduces a lot of distractions. I stripped down the [examples in apollo-fetch-upload](https://github.com/apollographql/apollo-fetch/tree/master/packages/apollo-fetch-upload#file-example), when I have a surplace of time I might update the examples here to be like that.
