### ISSUE TITLE
Scalar Upload generated type from graphql-binding as a string

### ISSUE THREAD

**Issue by thanatchakromsang** [jaydenseric/apollo-upload-server#101]
![2018-08-15-143201_1310x96_escrotum](https://user-images.githubusercontent.com/25862154/44136782-4a5c055e-a098-11e8-8995-9b8af521fa6b.png)

is it suppose to be like this below?
```typescript
export type Upload = {
      stream: NodeJS.ReadableStream
      filename: string
      mimtype: string
      encoding: string
}
```

**Comment by jaydenseric** [comment]
I'm not sure exactly what that library and the type is about, but the `Upload` scalar represents a Promise, that resolves an object like you noted (for the current version, it's about to change a little). It can't be serialized.

**Comment by thanatchakromsang** [comment]
@jaydenseric Thanks for short notice on the upcoming version!, as for the library it's an auto-generated type for schema but put that aside I still don't know what cause it to be like that

**Comment by jaydenseric** [comment]
Well, here is the source for the `GraphQLUpload` scalar: https://github.com/jaydenseric/apollo-upload-server/blob/v6.0.0-alpha.1/src/types.mjs#L3

Is there a way it can somehow be improved so auto-generated types are more useful? Does a type make sense in this context? Perhaps this is really an issue to be solved in the auto-type-generation library.

**Comment by mike-marcacci** [comment]
Hey @thanatchakromsang what generator are you using for that type system? Using [apollo-cli](https://github.com/apollographql/apollo-cli) you can use `--passthroughCustomScalars` and `--customScalarsPrefix` for both Flow and TypeScript generators, which allows you to define types for custom scalars.

For example, I use:


```ts
// @flow
declare type $GraphQLUpload = File | Blob;
```

**Comment by mike-marcacci** [comment]
(Didn't mean to close; hit the wrong button.)

**Comment by mike-marcacci** [comment]
OK, I see in your title that you're using `graphql-binding`. It looks like [this is a limitation of their generator](https://github.com/graphql-binding/graphql-binding/blob/d349174363a4bcdd88f5e6b8366d821cd579dadb/src/codegen/FlowGenerator.ts#L105), so I *am* going to close this here. They will likely need to implement better support for custom scalars on their end to get correct typing.

**Comment by thanatchakromsang** [comment]
@mike-marcacci Thanks for clearing that up for me :)
