### ISSUE TITLE
undefined properties when uploading using apollo-server-express

### ISSUE THREAD

**Issue by indieocean** [jaydenseric/apollo-upload-server#111]
I've been trying to add the upload feature to our graphql endpoint. We manage to hit the graphql mutation but the file stream is undefined. I can see on the developer tools that nothing is being sent in the request body which is odd. A console.log on the mutation server side renders { preview: 'blob:http://localhost:3000/ba021b5c-57e6-4fba-b574-a4933250b0c2' } and nothing else.

stream, filename, mimetype, encoding are all undefined.

## Mutation Field
```javascript 
uploadFile: {
    type: UploadType,
    args: {
      file: {
        type: GraphQLUpload
      }
    },
    async resolve(_, { file }) {
      const { stream, filename, mimetype, encoding } = await file;
      console.log(file);
      return {
        stream,
        filename,
        mimetype,
        encoding
      };
    }
  }
```

## Object Type
```javascript
const {
  GraphQLObjectType,
  GraphQLString
} = require('graphql');

const UploadType = new GraphQLObjectType({
  name: 'UploadType',
  fields: () => ({
    filename: {
      type: GraphQLString
    },
    mimetype: {
      type: GraphQLString
    },
    encoding: {
      type: GraphQLString
    }
  })
});

module.exports = UploadType;
```

## Mutation
```javascript
const UPLOAD_FILE = gql`
	mutation uploadFile($file: Upload!) {
		uploadFile(file: $file) {
			filename
		}
	}
`;
```

## Mutation Component
```
<Mutation mutation={UPLOAD_FILE}>
  {uploadFile => ( ... )}
</Mutation>
```

**Comment by mike-marcacci** [comment]
Hi @indieocean,

This sounds odd, indeed! Thanks for adding all this info here (although your preview link is to your local machine).

Just to be clear here, I would expect the result of your `console.log(file)` above to render a `Promise` object, rather than its results.

A few more questions:
- Where is the `GraphQLUpload` defined? I just want to make sure it's the `Upload` scalar exported by this package.
- What version of `apollo-server-express` are you using? (There are massive changes on their end for 2.0, including default bundling of this package.)
- If you're using `apollo-upload-server` directly, what version are you using?

**Comment by indieocean** [comment]
Yeah it seems pretty odd to us as well.

The GraphQLUpload is part of apollo-server-express 2.0.3 I can see the Upload scalar on the playground on the uploadFile mutation as well.

We are not using apollo-upload-server directly just thru apollo-server-express.

One thing to note is that we are using apollo-boost 0.1.14 which does the linkage automatically and all the magic happens behind the scenes. Perhaps there is an issue there? I dont see the apollo-upload-client on that package either.

**Comment by indieocean** [comment]
Update: I managed to remove apollo-boost that was the issue they don't provide the upload feature on it or at least I cant find how to enable it anywhere. I managed to get it to work with the following config.

```javascript
import React, { Component } from 'react';
import { ApolloProvider } from 'react-apollo';
import routes from './routes';
import { ApolloClient } from 'apollo-client';
import { InMemoryCache } from 'apollo-cache-inmemory';
import { onError } from 'apollo-link-error';
import { ApolloLink } from 'apollo-link';
import { createUploadLink } from 'apollo-upload-client'

const client = new ApolloClient({
  link: ApolloLink.from([
    onError(({ graphQLErrors, networkError }) => {
      if (graphQLErrors)
        graphQLErrors.map(({ message, locations, path }) =>
          console.log(
            `[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`,
          ),
        );
      if (networkError) console.log(`[Network error]: ${networkError}`);
    }),
    new createUploadLink({
      uri: process.env.REACT_APP_API_BASE_PATH
    })
  ]),
  cache: new InMemoryCache()
});

class App extends Component {
	render() {
		return (
			<ApolloProvider client={client}>
				{ routes }
			</ApolloProvider>
		)
	}
}

export default App;

```

**Comment by mike-marcacci** [comment]
Aah, that's interesting. This is probably something we should clarify in our docs – that if your query accepts an `Upload` rather than a (non-null) `Upload!` the argument can obviously be null instead of a `Promise`.

**Comment by jaydenseric** [comment]
Closing as the issue seems to be resolved, and related to the client and not the server anyway 😅
