### ISSUE TITLE
More properties in Upload resolver

### ISSUE THREAD

**Issue by Huvik** [jaydenseric/apollo-upload-server#112]
Hey, I wonder if there is some easy way to get more properties in `Upload scalar promise`, for example folder or something. So I can have for example `uploadFile(folder: String!, file: Upload!): File` and use it to store to different locations.

**Comment by mike-marcacci** [comment]
Hi @Huvik, you can already do this exactly! Awaiting the `file` argument doesn't have any effect on the `folder` argument. Perhaps I'm missing something though?

**Comment by Huvik** [comment]
@mike-marcacci Sorry for the question, but I figured it out by myself wrote the whole resolver. I was first trying to work with express middleware, but no luck.

**Comment by mike-marcacci** [comment]
No worries at all! Glad you got it solved :)

**Comment by acis** [comment]
@huv1k @mike-marcacci  I'm faced with the same question, for some reason I can't add another variable to the resolver.

This is my schema for the mutation

`upload(universityId: String!, file: Upload!): Boolean!`

and my POSTMAN curl request

`curl -X POST \
  'http://localhost:8080/graphql?=' \
  -H 'Accept: */*' \
  -H 'Host: localhost:8080' \
  -H 'content-length: 1811592' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
  -F 'operations={"query":"mutation addFile($file:Upload!, $universityId:String!){upload(file:$file, universityId:$universityId)}"}' \
  -F 'map={"0":["variables.file"], "1":["variables.universityId"]}' \
  -F '1="1"' \
  -F 0=@/Users/acis/Downloads/DSC_0144.JPG`

I'm getting following error 
`"message": "Variable \"$universityId\" got invalid value {}; Expected type String; String cannot represent a non string value: {}",`

I can't figure out how to send the universityId in the request. 
many thanks
