### ISSUE TITLE
"Unexpected token {", due to processRequest function definition syntax?

### ISSUE THREAD

**Issue by neekfenwick** [jaydenseric/apollo-upload-server#16]
Hi! First, thank you so much for this and the client module.  I'm using Node v7.5.0 **edit: correction, seems to be Node v4.8.4, inspecting process.version at runtime** and trying to add them to our Meteor based app and hit an early stumbling block with apollo-upload-server v2.0.4.  I add with `meteor npm install --save apollo-upload-server` and import as per your documentation, but the server fails to start with:

```
W20171013-09:34:07.929(7)? (STDERR) Debugger listening on [::]:45969
W20171013-09:38:24.349(7)? (STDERR) packages/modules.js:19849
W20171013-09:38:24.351(7)? (STDERR) function processRequest(request, { uploadDir } = {}) {
W20171013-09:38:24.353(7)? (STDERR)                                  ^
W20171013-09:38:24.354(7)? (STDERR) 
W20171013-09:38:24.355(7)? (STDERR) SyntaxError: Unexpected token {
W20171013-09:38:24.356(7)? (STDERR)     at Object.exports.runInThisContext (vm.js:53:16)
W20171013-09:38:24.357(7)? (STDERR)     at /home/me/app/.meteor/local/build/programs/server/boot.js:332:30
W20171013-09:38:24.358(7)? (STDERR)     at Array.forEach (native)
```

Setting a breakpoint for where this is being thrown, I see `runInThisContext` is part of the meteor bootstrapping process, and has:

`var func = require('vm').runInThisContext(wrapped, scriptPath, true);`

where `wrapped` is a large block of javascript code containing apollo-upload-server, containing:

```
function processRequest(request, { uploadDir } = {}) {
  // Ensure provided upload directory exists
  if (uploadDir) mkdirp.sync(uploadDir);
```

It looks like the `{ uploadDir } = {}` syntax is causing my node system to throw.  Is this new or in any way nonstandard syntax?  I'm fairly new to the latest es6 language features like destructuring.  Before adding your modules, the es6 style Meteor based server was running fine.

**Comment by neekfenwick** [comment]
I just noticed "Node >= 6.4" in the readme!  So I guess this issue is because of my Node v4.x.  I have a bad feeling Meteor is going to make it difficult for me to change Node versions, I'll go look.

**Comment by jaydenseric** [comment]
Thats right, it is due to to the old Node version not understanding modern ES syntax. Meteor uses a crazy old version of node, but you can upgrade to the latest pre-release; see https://github.com/jaydenseric/apollo-upload-server/issues/7#issuecomment-312150864 for more 🙂

**Comment by neekfenwick** [comment]
Thanks!  I forgot github hides closed comments and forgot to check there :( Sorry for the noise.  I had run into meteor's PR 8728 in the last hour and have been furiously building and updating things.  Now my Webstorm IDE cannot debug a Node v8.7.0 project.. but making progress :)
