### ISSUE TITLE
file extension problem

### ISSUE THREAD

**Issue by alewiahmed** [jaydenseric/apollo-upload-server#17]
First of all, Thanks. This is an amazing work. My problem is that When a file is uploaded the extension is removed. Why is that? I can see from the source code that it uses formidable. Making the keepExtensions: true inside the IncomingForm options makes it work. if we could set the keepExtensions field like the uploadDir filed it would be awesome.

**Comment by jaydenseric** [comment]
Glad you found this package helpfull 🙂

For the answer to your question, please see https://github.com/jaydenseric/apollo-upload-server/issues/14#issuecomment-334436357.
