### ISSUE TITLE
GraphQL operations is undefined

### ISSUE THREAD

**Issue by jstwrt** [jaydenseric/apollo-upload-server#19]
Hi, I'm having an odd case where the GraphQL operations are undefined when the multipart form request is parsed. We're using Google Cloud Functions at the moment. It works fine in my local GCF emulator but the deployed cloud version is always returning `undefined`.

**The code in question is:**

```
// Decode the GraphQL operation(s). This is an array if batching is
// enabled.
console.log( 'operations', operations )
operations = JSON.parse(operations)
```

As a result, the server logs the following:

```
...
SyntaxError: Unexpected token u in JSON at position 0 at Object.parse (native) at form.parse
...
Error: Request aborted at form.parse (/user_code/node_modules/@jstwrt/apollo-upload-server/lib/main/index.js:58:25)
```

Line 58 being `form.parse(request, (error, { operations }, files) => {`

Has anyone else experienced this issue. If someone could lead me in the right direction, that'd be helpful, thanks.

**Comment by jaydenseric** [comment]
Are you sure the multipart form is being sent with the all the usual fields?

**Comment by jstwrt** [comment]
Yeah, so running this in the local emulator, the request header looks like:

```
_header: 'POST /service-xxx/ HTTP/1.1\r\nhost: us-central1-xxx.cloudfunctions.net\r\ncontent-type: multipart/form-data; boundary=--------------------------915648292650779150376788\r\ncontent-length: 200979\r\nConnection: close\r\n\r\n'
```

But, having done some further research, it seems Google Cloud Functions may be the problem.

Referring to a recent StackOverflow post (last 2 days):

> Thanks for all the information provided. It seems that Cloud Functions might be having an issue with multipart/form-data. I'll be escalating your case to our engineers and I'll let you know once I get an update.

- https://stackoverflow.com/questions/47255820/firebase-functions-can-not-get-form-data
- https://stackoverflow.com/questions/47242340/how-to-upload-a-file-using-express-on-firebase-cloud-functions

I believe the library is not the problem, I'm in communication with the support engineers at Google. But for anyone else that may be experiencing this problem, the above may help.

Happy to close this off.
