### ISSUE TITLE
Resolver example in the README

### ISSUE THREAD

**Issue by koresar** [jaydenseric/apollo-upload-server#23]
Thanks for the great piece of tech!

I'm new to GraphQL and Apollo, thus having trouble understanding.
**Where would I put my code which streams data to S3?**

Should it be a mutation or something?

Would be great to have a typical file streaming example in the README to avoid similar questions from newbies.

Cheers

**Comment by jaydenseric** [comment]
Glad to help!

The streaming to S3 should happen in your resolver for the whatever you call your upload mutation.

In the example [here](https://github.com/jaydenseric/apollo-upload-examples/blob/master/api/resolvers.mjs#L48), the `file` mutation argument is an `Upload` scalar (see [here](https://github.com/jaydenseric/apollo-upload-examples/blob/master/api/schema.mjs#L17) in the scema). You need to await the upload scalar like [here](https://github.com/jaydenseric/apollo-upload-examples/blob/master/api/resolvers.mjs#L37), so you can get the stream out of it. That is the file stream you can push up to S3.

I don't use S3, but looking at their JS SDK docs, it looks like you can upload the file stream like [this](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property).

Hope that helps!

**Comment by koresar** [comment]
Nice links! I wish I knew earlier there is an example. 😀
Should I submit a READMEA.md PR to point to the apollo-upload-examples repo?

**Comment by jaydenseric** [comment]
Thanks for the offer, although there is a link in the [usage section](https://github.com/jaydenseric/apollo-upload-server#usage) already:

> See the [example API and client](https://github.com/jaydenseric/apollo-upload-examples).

Happy to review a PR that might make things a little clearer or easier.

Maybe the most value would be another mutation in the example API that uploads to S3, so we have one example for local filesystem storage and one for cloud. Not sure if S3 would allow a demo for free though.

**Comment by koresar** [comment]
S3 example is not necessary as long as there is an example showing how I obtain a `ReadableStream` and pipe it somewhere.
All good.

Please, see PR #24
