### ISSUE TITLE
Only absolute urls are supported in example. And get empty object istead of file.

### ISSUE THREAD

**Issue by polodrawsshowing** [jaydenseric/apollo-upload-server#25]
In your example
![screen shot 2017-12-04 at 20 46 31](https://user-images.githubusercontent.com/24593520/33570084-5f13b66c-d934-11e7-81bc-5f32b00facd4.png)
Client logs:
![screen shot 2017-12-04 at 20 46 19](https://user-images.githubusercontent.com/24593520/33570109-74b23340-d934-11e7-88f2-14dfad37f4c4.png)
When i'm trying to make same thing on my server and client. I got empty object istead of file :(
![screen shot 2017-12-04 at 20 49 07](https://user-images.githubusercontent.com/24593520/33570156-9b8625c6-d934-11e7-878a-91ae2a05c629.png)
Any ideas?

**Comment by jaydenseric** [comment]
Just looking at the resolver screenshot, it seems you are missing `await`:

```js
const { stream, filename, mimetype, encoding } = await avatar
```

**Comment by jaydenseric** [comment]
Did you end up getting to the bottom of this one?

**Comment by jaydenseric** [comment]
We can reopen if the plot thickens 🙂
