### ISSUE TITLE
Uploaded file variable expected "Promise" object, but "false".

### ISSUE THREAD

**Issue by async3619** [jaydenseric/apollo-upload-server#27]
currently, I'm using express to use apollo-upload-server middleware. but It works quite strange. the file variable in resolver has "false" value not a "promise".

I've checked with my own middleware to check how `apolloUploadExpress(/* ... */)` middleware set a `variables` object. and It successfully assigned `promise` but It changes from `promise` to `false` when it passed to resolver function. 

right below code snippet is my own middleware code:
```js
app.use("/graphql",
    bodyParser.json(),
    apolloUploadExpress(),
    (request, _, next) => {
        console.log(request.body.variables.thumbnail); // this prints 'Promise { ... }'
        next();
    },
    graphqlExpress({
        schema: require("./schema"),
    }),
);
```

and this is resolver code:
```js
{
    push: async (_, args) => {
        // the 'thumbnail' variable accepted as file.
        const { thumbnail } = args;

        // so we could expect that right below code snippet will prints about "Promise" object.
        // but just prints "false".
        console.log(thumbnail);
    },
};
```

*EDIT*

I'm using both server and client in a same project.
and I've tested that Promise can be resolved in my own middleware function.
but it still pass a 'false' value instead of 'Promise' to resolver callback.

**Comment by jaydenseric** [comment]
Are both the server and client packages at the latest alpha versions?

**Comment by async3619** [comment]
@jaydenseric 

yes.

```js
        "apollo-upload-client": "^7.0.0-alpha.1",
        "apollo-upload-server": "^4.0.0-alpha.1",
```

**Comment by async3619** [comment]
Solved.

I didn't specify `Upload: GraphQLUpload` item on resolvers object when I make executable schema. yeah, I Know It's too pathetic mistake to tell. by the way, thanks for helping me out.

**Comment by jaydenseric** [comment]
Glad it was an easy fix 😅
