### ISSUE TITLE
How to use it with apollo-server-lambda?

### ISSUE THREAD

**Issue by human-a** [jaydenseric/apollo-upload-server#28]
Hi

This is super great, I am just wondering how I can use it with [apollo-server-lambda](https://github.com/apollographql/apollo-server/tree/master/packages/apollo-server-lambda) since I am spinning up my graphql server on a lambda function.

**Comment by jaydenseric** [comment]
Hi there, sorry for the late reply!

Thats a good question, I have no experience with it.

Does it use middleware somehow? If so, and if the existing middleware exports won't work you might be able to write your own using [`processRequest`](https://github.com/jaydenseric/apollo-upload-server#custom-middleware).

If it turns out there is something we can do here to improve compatibility we can reopen 🙂

**Comment by mlecoq** [comment]
Hi, 

I also use [apollo-server-lambda](https://www.npmjs.com/package/apollo-server-lambda) with serverless and need to upload file. 

Here is my handler:


```
export const reports: Handler = (event, context, callback) => {

  const requestOrigin = event.headers.origin,
    callbackFilter = function(error, output) {
      output.headers['Access-Control-Allow-Origin'] = '*';
      output.headers['Access-Control-Allow-Credentials'] = 'true';
      callback(error, output);
    };

  const headers = event.headers,
    functionName = context.functionName;

  const handler = graphqlLambda({
    schema,
    context: {
      headers,
      functionName,
      event,
      context,
    },
  });

  return handler(event, context, callbackFilter);
};
```


processRequest is not usable on event 

```
(node:23039) UnhandledPromiseRejectionWarning: Error: Missing Content-Type
    at new Busboy (/Users/mickaellecoq/git/fo_api_reports/.webpack/service/webpack:/node_modules/busboy/lib/main.js:24:1)
    at Promise (/Users/mickaellecoq/git/fo_api_reports/.webpack/service/webpack:/node_modules/apollo-upload-server/lib/middleware.mjs:45:1)
```



My event has a content type in the headers:


```
 event: { headers:
   { Host: 'localhost:3000',
     'User-Agent': 'insomnia/5.16.6',
     'Content-Type': 'application/json',
     Authorization: 'xxxx',
     Accept: '*/*',
     'Content-Length': '270' },
  path: '/reports',
  pathParameters: null,
  requestContext:
   { accountId: 'offlineContext_accountId',
     resourceId: 'offlineContext_resourceId',
     apiId: 'offlineContext_apiId',
     stage: 'api',
     requestId: 'offlineContext_requestId_53885019608724',
     identity:
      { cognitoIdentityPoolId: 'offlineContext_cognitoIdentityPoolId',
        accountId: 'offlineContext_accountId',
        cognitoIdentityId: 'offlineContext_cognitoIdentityId',
        caller: 'offlineContext_caller',
        apiKey: 'offlineContext_apiKey',
        sourceIp: '127.0.0.1',
        cognitoAuthenticationType: 'offlineContext_cognitoAuthenticationType',
        cognitoAuthenticationProvider: 'offlineContext_cognitoAuthenticationProvider',
        userArn: 'offlineContext_userArn',
        userAgent: 'insomnia/5.16.6',
        user: 'offlineContext_user' },
     authorizer:
      { principalId: 'offlineContext_authorizer_principalId',
        claims: [Object] },
     resourcePath: '/reports',
     httpMethod: 'POST' },
  resource: '/reports',
  httpMethod: 'POST',
  queryStringParameters: null,
  stageVariables: null,
  body: '{"query":"mutation {\\n\\taddAttachment(\\n\\t\\tattachment: {\\n\\t\\tattachment_id: \\"2\\",\\n\\t\\tcriterion_id: \\"2\\",\\n\\t\\treport_id: \\"2\\",\\n\\t\\tfiles: [{name:\\"plip\\", url:\\"ploup2\\"}]\\n\\t}){\\n\\t\\tattachment_id,\\n\\t\\tvalue\\n\\t\\tfiles {\\n\\t\\t\\tname\\n\\t\\t\\turl\\n\\t\\t}\\n\\t}\\n}"}',
  isOffline: true }

```

I am wondering what would be the best solution : a modification in apollo-upload-server to support middleware (and then use process-request on it) or a specific method in apollo-upload-server

If a specific method in apollo-upload-server is the best solution, how would you proceed ? ( and then I could take in charge the implementation)

**Comment by mlecoq** [comment]
I am trying to merge processRequest with what is explained here :  [https://develandoo.com/blog/2017/06/16/parsing-multipart-body-aws-lambda-function-serverless/](https://develandoo.com/blog/2017/06/16/parsing-multipart-body-aws-lambda-function-serverless/)

I understand why I had the issue on Content-Type.

Now I try to figure out how replace `request.pipe(parser)` in processRequest for a newly created processEvent method
