### ISSUE TITLE
How to use with Meteor GridFS?

### ISSUE THREAD

**Issue by windgaucho** [jaydenseric/apollo-upload-server#29]
Hello, awesome project !!

I am using apollo with meteor and I have successfully integrated your package with apollo and meteor.
Can you please give an example on how to use the internal meteor gridfs to save the received file?

Thank you

**Comment by jaydenseric** [comment]
Hi 👋 and thanks 😊

I don't use Meteor myself, but @joncursi might be able to share some pointers. Specific examples for the new streaming API might be more tricky to come by, since not everyone has upgraded yet.

**Comment by joncursi** [comment]
Ah, unfortunately I am not using GridFS in my Meteor implementation so unfortunately I am unable to comment. Personally, I am using the AWS SDK to upload the files to S3.

**Comment by windgaucho** [comment]
Thank you anyway guys, I will try to figure out.

**Comment by viiiprock** [comment]
I intend to optimize image using `sharp js`, it's has optimize to buffer function, don't know if it could use as middleware to store buffer in GridFS.

**Comment by jaydenseric** [comment]
Closing this question due to inactivity. A good place to ask general usage questions is the [Apollo Slack #uploads channel](https://apollographql.slack.com/messages/uploads) 🙂
