### ISSUE TITLE
Payload Verification?

### ISSUE THREAD

**Issue by tim-soft** [jaydenseric/apollo-upload-server#34]
This may seem like a silly question but I am rather new to this lib. Are there any checks that take place to verify that the only files received by the server are those purposefully sent by the client?

I'm imagining a scenario where a MITM could try to add files to the request that do not match what was extracted from the query string.

Absolutely love this application of graphql!

**Comment by jaydenseric** [comment]
Well, in the PR for the new version malformed requests (additional unexpected file fields) are tested for and are handled gracefully. As for a malicious person who understands the spec manipulating the request, would that not be solved by HTTPS?

**Comment by jaydenseric** [comment]
This question has been answered, but feel free to keep discussing 🙂
