### ISSUE TITLE
How to use with AdonisJs?

### ISSUE THREAD

**Issue by mastito03** [jaydenseric/apollo-upload-server#38]

**Comment by jaydenseric** [comment]
I have no experience with it, but am happy to answer any questions that might come up if you would like to take a stab at it.

**Comment by jaydenseric** [comment]
Closing this question due to inactivity. A good place to ask general usage questions is the [Apollo Slack #uploads channel](https://apollographql.slack.com/messages/uploads) 🙂

**Comment by rafaelfesi** [comment]
@mastito03 Did you solve it?

**Comment by mastito03** [comment]
right now i use Custom middleware and load it from router

**Comment by rafaelfesi** [comment]
@mastito03 Could you give me an example of the Middleware and router with this?
