### ISSUE TITLE
Support regular clients again

### ISSUE THREAD

**Issue by Thammada** [jaydenseric/apollo-upload-server#4]
I guess `operations` [here](https://github.com/jaydenseric/apollo-upload-server/blob/master/src/index.js#L21) would be undefined when using a client other than apollo-upload-client

> undefined:1
> undefined
> ^
> 
> SyntaxError: Unexpected token u in JSON at position 0
>     at Object.parse (native)
>     at form.parse (/Users/t/apps/thai.run-api/node_modules/apollo-upload-server/dist/apollo-upload-server.js:29:25)
>     at IncomingForm.<anonymous> (/Users/t/apps/thai.run-api/node_modules/formidable/lib/incoming_form.js:102:9)
>     at emitOne (events.js:96:13)
>     at IncomingForm.emit (events.js:188:7)
>     at IncomingForm._error (/Users/t/apps/thai.run-api/node_modules/formidable/lib/incoming_form.js:290:8)
>     at IncomingMessage.<anonymous> (/Users/t/apps/thai.run-api/node_modules/formidable/lib/incoming_form.js:120:12)
>     at emitNone (events.js:86:13)
>     at IncomingMessage.emit (events.js:185:7)
>     at abortIncoming (_http_server.js:283:11)
>     at Socket.serverSocketCloseListener (_http_server.js:296:5)
>     at emitOne (events.js:101:20)
>     at Socket.emit (events.js:188:7)
>     at TCP._handle.close [as _onclose] (net.js:498:12)

**Comment by jaydenseric** [comment]
You're quite right, with the new version that I rushed out to support query batching clients not using `apollo-upload-client` won't work. I am [aware of the issue](https://github.com/jaydenseric/apollo-upload-client/issues/1#issuecomment-289773582), have been feeling quite guilty about it and expect to resolve it this weekend.

Sorry!
