### ISSUE TITLE
Understanding options

### ISSUE THREAD

**Issue by tatianacmh** [jaydenseric/apollo-upload-server#41]
Hello,

I want to thank you for this package. But I have a few questions:

I wanted to know what do you mean with this option:
`maxFieldSize: Max allowed non-file multipart form field size in bytes `

Also, is it possible to have an example on how can I test this in the server side (automatic tests)? 

Thanks.

**Comment by jaydenseric** [comment]
`maxFieldSize` basically needs to be large enough to contain the queries and variables of your request. This will usually be quite small. But if you batch many, massive queries, or if some variables hold massive strings you might hit a conservative limit. You can see in the [GraphQL multipart request spec](https://github.com/jaydenseric/graphql-multipart-request-spec#multipart-form-field-structure) that for all requests there are only two non-file fields that `maxFieldSize` applies to; `operations` and `map`.  Under the hood `maxFieldSize` is fed to [`busboy` `config.limits.fieldSize`](https://github.com/mscdex/busboy#busboy-methods).

You can see how I use AVA to test `apollo-upload-server` [here](https://github.com/jaydenseric/apollo-upload-server/blob/v4.0.2/src/test.mjs#L31). You might also find the [cURL examples](https://github.com/jaydenseric/graphql-multipart-request-spec#curl-request) in the GraphQL multipart request spec handy.

Testing `apollo-upload-client` is in some ways impossible, as `FileList`, `File` and `Blob` don't exist as globals in Node.js. [`extract-files` is partially tested](https://github.com/jaydenseric/extract-files/blob/v3.1.0/src/test.mjs), and that is where the complicated recursion logic lives.
