### ISSUE TITLE
JavaScript Schema

### ISSUE THREAD

**Issue by noamalffasy** [jaydenseric/apollo-upload-server#42]
I'm currently using a JavaScript schema and I don't want to rewrite as GraphQL, Your examples don't show how to implement the Upload scalar using JavaScript.
Are you able to do an example showing how to implement it using JavaScript?
It will help me and probably other people.

**Comment by jaydenseric** [comment]
I've never done it. Would someone who has like to share?

**Comment by noamalffasy** [comment]
I ended up fixing it by importing the GraphQLUpload from the library and attaching it to the type like so: 

```js
import { GraphQLUpload } from "apollo-upload-server"; 

const Upload = GraphQLUpload;
```
