### ISSUE TITLE
App reload itself after uploading done

### ISSUE THREAD

**Issue by Altiano** [jaydenseric/apollo-upload-server#43]
I'm not really sure what happen to my client app (frontend).. 
If the resolver in the backend perform `await processUpload(...)` and succeed the client will reload itself.

It's hard to debug what the response from the backend was.
Because using Chrome Devtools, the network tab also reloaded.

Does this package send`Refresh HTTP Header` or something else happen in the backend that cause this? 

PS: I'm using `express` with middlewares: (in order) `bodyParser.json()` `bodyParser.urlencoded({ extended: true })` `cookieParser(theSecret)` `compress()` `methodOverride()` `session({..})` `passport.initialize()` `passport.session()` `helmet()` `cors()` `expressWinston.logger({..})` `rest` `graphql` `graphiql`

**Comment by jaydenseric** [comment]
Nothing jumps to mind, there is a lot going on there. Are you able to narrow down the minimal steps needed to reproduce the issue?

**Comment by Altiano** [comment]
I think the problem is in this code below (the `resolver`):
```

resolvers: {
Mutation: {
createUser: async (_, { inputData: { picture } }) => {

    try {
      await processUpload({ picture })

      // This line was never called
      return {msg: 'Success'}

    } catch (error) {
      throw error
    }
  },
}
}
```
after the `processUpload()` done so is the execution of this resolver.
Anyidea?

**Comment by jaydenseric** [comment]
Perhaps there is something wrong in `processUpload` causing it to never resolve.

**Comment by Altiano** [comment]
Aha!

2 problems:

1. The order of event listener on picture stream (`.on('error'` and `on.('end'`) is wrong. It listened on those events after `writeStream`

2. This is the most important. The uploaded files transfered to my app directory, which cause my app server to reload because it detects file chages

#Damn
