### ISSUE TITLE
if wrap next.js it can't upload the file

### ISSUE THREAD

**Issue by polo13999** [jaydenseric/apollo-upload-server#44]
if wrap the next.js  resolver can get file but can't save to Upload path 
https://github.com/polo13999/apolloUpload

**Comment by jaydenseric** [comment]
Can you please explain the issue in a little more detail?

**Comment by jaydenseric** [comment]
This can be reopened if a specific issue and minimal reproduction steps is provided.

For people wondering, Next.js is fully supported and is part of the official [example app](https://github.com/jaydenseric/apollo-upload-examples#web-app).
