### ISSUE TITLE
FileMissingUploadError: File missing in the request

### ISSUE THREAD

**Issue by smithaitufe** [jaydenseric/apollo-upload-server#47]
Please how do we make FileUpload optional?

**Comment by jaydenseric** [comment]
Could you please provide example for how to reproduce that error?

Here is [an answer](https://github.com/jaydenseric/graphql-multipart-request-spec/issues/9#issuecomment-364825859) for someone else asking a somewhat related question.

**Comment by jaydenseric** [comment]
`FileMissingUploadError` should only happen if the multipart request is malformed and does not match [the spec](https://github.com/jaydenseric/graphql-multipart-request-spec). Something unlikely to happen if `apollo-upload-client` is forming the request.

If you meant the question in the basic GraphQL sense, you can make an `Upload` scalar optional by not putting an `!` next to it.

**Comment by luciomr** [comment]
@jaydenseric the referenced answer did it for me. My Upload parameter was made optional by not adding the `!` next to it, but I was still getting the error because in Postman I was still indicating in my multipart request that there was a file to be expected in the map line.
Leaving the value of `map` as an empty array (`{"0": []}`) and giving a value of `null` to the file parameter in the `operations` part of the form request fixed it for me.

**Comment by EhsanSarshar** [comment]
I have this issue with ReactNativeFile

**Comment by amosbastian** [comment]
@EhsanSarshar did you manage to solve it? I'm having the same problem 😓

**Comment by EhsanSarshar** [comment]
@amosbastian I think for me it was a bug in one version on react native. so after releasing a patch I just upgrade and the error gone.

**Comment by Yemisrach15** [comment]
> I had this problem in React Native (Android). The problem for my case happened when Android couldn't get the `filename` of the photo, so the `name` property in ReactNativeFile construction was undefined. My fix was to patch the `name` property like so:
> 
> ```js
>   {
>         uri: image.path,
>         type: image.mime,
>         name: image.filename || `${Date.now()}.${image.mime.split('/')[1]}`,
>    }
> ```
> 
> Although [the typing of ReactNativefile](https://github.com/jaydenseric/apollo-upload-client#type-reactnativefilesubstitute) suggest that both the `type` and `name` property could be undefined, `graphql-upload` obviously doesn't like that.

Thank you for this reallly. I was close to giving up
