### ISSUE TITLE
is there any example for express?

### ISSUE THREAD

**Issue by phakphumi** [jaydenseric/apollo-upload-server#48]
I am trying to find the way to upload a file using your package but I don't know how to define the schema and resolver, also how to test if it works (normally I test it on graphiql).

please, anyone can provide an example for me.

**Comment by jaydenseric** [comment]
You set up the Express middleware like [this](https://github.com/jaydenseric/apollo-upload-server#express).

The schema and resolvers look the same in any Node.js server; you can see an example [here](https://github.com/jaydenseric/apollo-upload-examples/blob/master/api/server.mjs#L17).
