### ISSUE TITLE
Add possibility to rename Upload scalar

### ISSUE THREAD

**Issue by vladshcherbin** [jaydenseric/apollo-upload-server#49]
Hey,

It would be great to have a possibility to rename scalar. I tried this code, but it is still named `Upload`:

```js
import { GraphQLUpload } from 'apollo-upload-server'

const imageTypeDefs = `
  scalar Image
`

const imageResolvers = {
  Image: GraphQLUpload
}
```

**Comment by jaydenseric** [comment]
I like the convention of `Upload` being a defacto standard scalar; we don't want to encourage renaming it.

Perhaps being able to rename the `Upload` scalar would be useful if integrating uploads into an API that already has a scalar of the same name, but it looks like this is not your use case.

`Image` is not a good idea for a rename. Semantically it is not an image. The scalar is a Promise for an upload of any file type. If later on you need to upload non-image files to your API the name `Image` no longer makes sense. `Image` is better reserved for a type about an actual image, which might have properties such as `url`, `width`, `height`, etc.

**Comment by vladshcherbin** [comment]
@jaydenseric yep, `Image` was just a bad example. I actually like `FileUpload` and wanted to use it instead of just `Upload`.

**Comment by vladshcherbin** [comment]
@jaydenseric hm, but if I want to make it possible to receive only files, I can forbid blobs in resolver, right?

**Comment by jaydenseric** [comment]
That would be validation of the contents of the scalar, just like an invalid or valid email address is still a `String` scalar.

**Comment by jaydenseric** [comment]
We could export a new `createUploadScalar()` API, and export the standard scalar using `createUploadScalar('Upload')`.

Alternatively, people could `import { GraphQLScalarType } from 'graphql'` (already a peer dep in their app) and copy [how to create the scalar from scratch](https://github.com/jaydenseric/apollo-upload-server/blob/v4.0.2/src/types.mjs#L5) and name it whatever.

**Comment by vladshcherbin** [comment]
@jaydenseric okay, so basically, if I want to accept only files in this scalar (or only file with image type), I need to use a custom scalar instead of `GraphQLUpload` which invalidates blobs, etc?

**Comment by vladshcherbin** [comment]
@jaydenseric yep, now I get it, `GraphQLUpload` is just a default resolver for `Upload` scalar and if I want to restrict it (to accept only files/images/etc) I need to write a custom one instead.

Thank you for clearing things out 🙏

**Comment by jaydenseric** [comment]
The best way to validate uploads is to do it the same way you would for any mutation argument; in the mutation resolver.

For example:

```graphql
scalar Upload

type Image {
  filename: String!
  # width: Int!
  # height: Int!
  # url: String!
}

uploadImage (image: Upload!): Image!
```

In the `uploadImage` mutation resolver:

```js
(obj, { image }) => {
  const { stream, filename, mimetype, encoding } = await image

  if (mimetype !== 'image/png') throw new Error('Must be an image file!')

  // Handle stream, etc. then eventually:

  return {
    filename
    // width
    // height
    // url
   }
}
```

**Comment by vladshcherbin** [comment]
@jaydenseric yep, I'll validate the file input in input component and in mutation 👍 

Still don't like the `Upload` title, it makes me feel so uncomfortable inside. It's a custom type and I understand `Date`, `Blob` types, but what is an `Upload` type. Since it accepts files, blobs I don't know how to name it better, though :(

**Comment by vladshcherbin** [comment]
@jaydenseric thank you, this will definitely help 👍
