### ISSUE TITLE
Could you support documentation on how to use this project with

### ISSUE THREAD

**Issue by reduxdj** [jaydenseric/apollo-upload-server#50]
https://reactql.org/docs/

I tried from your example but it I got hung up on scalars and the different way you defined your schema, were using graphql.js and it's not to easy trying to shoe-horn your library in.

**Comment by green-coder** [comment]
Please describe your question precisely.

**Comment by jaydenseric** [comment]
I think it's a lot easier than it may seem; going off https://github.com/jaydenseric/apollo-upload-server/issues/42. Just import the `GraphQLUpload` scalar and use it, like any other scalar?

Happy to review a PR to explain this in the "[Upload scalar](https://github.com/jaydenseric/apollo-upload-server#upload-scalar)" readme section, as use of `graphql-tools` is currently assumed. This project is named "***apollo***-upload-server" afterall 😛

To make this package more generic I have been considering dropping `apollo` from the name. Currently the middleware should work for both Apollo and the reference GraphQL server, although I have only ever used Apollo server.
