### ISSUE TITLE
Cannot upload image on localhost server

### ISSUE THREAD

**Issue by Reyhanahmed** [jaydenseric/apollo-upload-server#52]
I am trying to upload an image on my graphql server. The way I am doing is as follows;

My component looks like this;
```class FileUpload extends Component {
	handleImageUpload = async ([file]) => {
		console.log('file: ', file);
		const res = await this.props.uploadImageMutation({
			variables: { file },
		});
		console.log('res: ', res);
	};
	render() {
		const { children, disableClick } = this.props;
		return (
			<Dropzone className="ignore" onDrop={this.handleImageUpload} disableClick={disableClick}>
				{children}
			</Dropzone>
		);
	}
}

const UPLOAD_IMAGE_MUTATION = gql`
	mutation UploadImageMutation($file: Upload!) {
		singleUpload(file: $file)
	}
`;

export default graphql(UPLOAD_IMAGE_MUTATION, { name: 'uploadImageMutation' })(FileUpload);
```

Schema:
```
scalar Upload

type Mutation {
	singleUpload(file: Upload!): Boolean!
}
```

And resolver is as follow;
```
{
       Upload: GraphQLUpload,
       Mutation: {
              singleUpload: async (parent, { file }) => {
                 const fil = await file;
                 return true;
              },
       }
}
```

When I upload the image I get the response true but cannot see the upload file on my server. If someone could point out what I am doing wrong that would be really helpful. Thanks!

**Comment by rstrom** [comment]
Rey, the file object is a promise, so you need to reference it like. `const { stream, filename, mimetype, encoding } = await file;` Maybe that helps?

**Comment by Reyhanahmed** [comment]
@rstrom yeah I've done that. But isn't there suppose to be an uploaded file on my local server? I can't find that file. :(

**Comment by rstrom** [comment]
Ah no, the file is transmitted as a stream, so you need to send that somewhere like S3 or your local filesystem. It's not stored automatically.

**Comment by Reyhanahmed** [comment]
@rstrom thank you so much for the reply. Got it working :)

**Comment by AyeChanPhyo** [comment]
i still have that problem. i can't find my file in that directory . Any suggestion ?
