### ISSUE TITLE
Not possible to use with TypeScript

### ISSUE THREAD

**Issue by pleerock** [jaydenseric/apollo-upload-server#53]
Since apollo is written on typescript lot of people are using it with typescript. Solution is to rewrite this library in typescript with minimal changes which is easy to do or include and maintain typescript typings.

**Comment by jaydenseric** [comment]
How do you mean this package is "not possible to use with TypeScript"?

**Comment by pleerock** [comment]
its possible, however there are no types and things must be typed with "any"

**Comment by jaydenseric** [comment]
Thanks for the suggestion, but for a variety of reasons this project is intentionally vanilla JS; Flow or TypeScript typings will never be added.

`import` works, even natively in Node.js thanks to `.mjs`. If there really is an issue importing from within a TypeScript project please file an issue to that effect, outlining reproduction steps and ideally and explanation or links to relevant TypeScript compiler issues.

**Comment by purplemana** [comment]
Here's a partial definitions file in case you are using this as part of a graphql-yoga project:

**Comment by mike-marcacci** [comment]
Types are now available by adding the `@types/graphql-upload` package.

**Comment by YannisMarios** [comment]
@mike-marcacci 

FileUpload type is not included in @types/graphql-upload?

**Comment by mike-marcacci** [comment]
@YannisMarios https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37542

**Comment by elie222** [comment]
Seems to conflict with the ts types defined in the `graphql-upload` package.

**Comment by jaydenseric** [comment]
@elie222 there are no TypeScript types defined in the `graphql-upload` package. Perhaps you mean the JSDoc types, that are used for documentation purposes in the readme? There are no JSDoc comments in the published code, so TS shouldn't be confused by them.

**Comment by elie222** [comment]
Hmm. That’s strange because I just deleted a ts file with old types from my
node modules. Maybe if clear my node modules and reinstall it all it will
work.

**Comment by elie222** [comment]
Confused as to why it's grabbing old types from Apollo:

![image](https://user-images.githubusercontent.com/3090527/62983966-f7201900-be39-11e9-8494-1134af4dfd5d.png)
![image](https://user-images.githubusercontent.com/3090527/62983973-fe472700-be39-11e9-9f89-3f732dff2f96.png)

**Comment by goulkreek** [comment]
Ideally typescript definition should be included in directly in module.
Suggestions:
* add index.js to allow import of any graphql-upload components (to prevent importing source file directly like `import graphqlUploadExpress from 'graphql-upload/graphqlUploadExpress.mjs'`
* export components (like FileUpload, graphqlUploadExpress, etc) without "default exports".
Without that, unfortunately cannot upgrade graphql-upload to a version greater that 13.0.0
thx in advance
