### ISSUE TITLE
Files don't save

### ISSUE THREAD

**Issue by oasis1992** [jaydenseric/apollo-upload-server#54]
I get this in my resolve

`Promise {
  { stream:
   FileStream {
     _readableState: [ReadableState],
     readable: true,
     domain: null,
     _events: [Object],
     _eventsCount: 2,
     _maxListeners: undefined,
     truncated: false,
     _read: [Function] },
  filename: 'Captura de pantalla 2018-02-19 a la(s) 18.31.42.png',
  mimetype: 'image/png',
  encoding: '7bit' } }`

**Comment by jaydenseric** [comment]
That is how it works, the resolver recieves [a promise that resolves amongst other metadata, a file stream](https://github.com/jaydenseric/apollo-upload-server#upload-scalar) which you can use to [store the file locally on the filesystem](https://github.com/jaydenseric/apollo-upload-examples/blob/master/api/resolvers.mjs#L42) or pipe it into a cloud API.

**Comment by oasis1992** [comment]
very thanks
