### ISSUE TITLE
mimetype is always 'application/octet-stream'

### ISSUE THREAD

**Issue by rlataguerra** [jaydenseric/apollo-upload-server#59]
The mimetype always appear to be defined as 'application/octet-stream'

**Comment by jaydenseric** [comment]
Even when there are no uploads?

**Comment by rlataguerra** [comment]
tbh I did not check without upload

**Comment by jaydenseric** [comment]
We can reopen to investigate if you are still having an issue and are able to provide specific reproduction steps that highlight what happens, vs what is expected to happen 😌
