### ISSUE TITLE
Does not work with Apollo Launchpad

### ISSUE THREAD

**Issue by pleerock** [jaydenseric/apollo-upload-server#61]
If you simply import this library in launchpad:

```
import "apollo-upload-server";
```

 it fails with following error:

```json
{
  "code": 400,
  "error": "Script returned an error.",
  "details": "ReferenceError: Invalid left-hand side in assignment",
  "name": "ReferenceError",
  "message": "Invalid left-hand side in assignment",
  "stack": "ReferenceError: Invalid left-hand side in assignment\n    at exports.runInThisContext (vm.js:53:16)\n    at Module._compile (module.js:373:25)\n    at Module._compile (/data/sandbox/lib/module.js:127:21)\n    at Object.Module._extensions..js (module.js:416:10)\n    at Module.load (module.js:343:32)\n    at Function.Module._load (module.js:300:12)\n    at Module.require (module.js:353:17)\n    at require (internal/module.js:12:17)\n    at Object.<anonymous> (/data/_verquire/apollo-upload-server/5.0.0/node_modules/apollo-upload-server/lib/index.js:19:19)\n    at Module._compile (module.js:409:26)"
}
```

https://launchpad.graphql.com/w50x0j5x4z

**Comment by jaydenseric** [comment]
It could be an issue with Launchpad. Just a random guess, but maybe they don't provide an up to date `graphql` peer dependency? Often Apollo projects take a while to support the latest version. [It must be >= v0.13.1](https://github.com/jaydenseric/apollo-upload-server/blob/v5.0.0/package.json#L40).

The Launchpad error trace doesn't reveal anything actionable, but feel free to dig more into it and we can reopen if you manage to find a bug relating to this package 🙏
