### ISSUE TITLE
make errors as extensions of GraphQLError

### ISSUE THREAD

**Issue by joesanta555** [jaydenseric/apollo-upload-server#62]
When I upload a file bigger than maxFileSize the entire app crashes with this error:

MaxFileSizeUploadError: File truncated as it exceeds the size limit.

would it be better to throw GraphQLError instead so user will get a feedback and not crash the server?

**Comment by jaydenseric** [comment]
Duplicates https://github.com/jaydenseric/apollo-upload-server/issues/45.

**Comment by joesanta555** [comment]
I have read the #45 before and updated to the latest version. But it is not throwing the error type: GraphQLError. If it would trow GraphQLError the resolver would return it as an error to the client and not crash the api.

**Comment by jaydenseric** [comment]
We need a way to handle the error as a stream event, so that when an upload stream to a cloud service suddenly cuts off due to the file size limit it can be handled properly (cleanup, etc.).

It is really up to the developer how the error should be communicated to the client; I don't throw validation errors in my resolvers (resulting in a GraphQL error). Instead I populate an errors field in the response payload. Something [like this](https://github.com/jaydenseric/apollo-upload-server/issues/49#issuecomment-367172954).

**Comment by joesanta555** [comment]
Thank you for your response.

I still do not know how to know if en error is from your library or not.

copy&paste from your link:

```js
  if (
    // Image stream was truncated due to maxFileSize
  ) payload.errors.image.push('Filesize too big.')
```

how do I know the Image stream was truncated due to maxFileSize or some other error was thrown from your library? Where should I do the try{} catch{} ?

It would be nice if the I could catch error here like this and re-throw it:
```js
    try {
      const { stream, filename, mimetype, encoding } = await data.image;
    } catch (error) {
      throw new GraphQLError(error.message);
    }
```

Sorry again for lame questions I am new to node/graphql...

Thank you very much for taking your time of your busy day doing great packages.

**Comment by jaydenseric** [comment]
In theory, you should be able to do this:

```js
// Individual file upload stream
stream.on('error', error => {
  if (stream.truncated) console.log('Cut off for some reason.')
  // Or…
  if (error.name === 'MaxFileSizeUploadError') console.log('Cut off specifically due to exceeded max file size')
})
```

But, there is that bug causing the server to crash instead.

One possible fix I could do is to change the API, so that the `MaxFileSizeUploadError` does not cause an `error` event:

```js
stream.on('limit', error => { })
```
