### ISSUE TITLE
"SyntaxError: Unexpected token {"

### ISSUE THREAD

**Issue by alexter42** [jaydenseric/apollo-upload-server#7]
Just tried to import  "apollo-upload-server" in a new blank meteor project (v1.5) and it still throwing this error:
error "function processRequest(request, { uploadDir } = {}) {"
"SyntaxError: Unexpected token {"

The error is shown when trying to import 'apollo-upload-server' to 'server/main.js'.
Any thoughts?

**Comment by jaydenseric** [comment]
What version of Node are you using?

**Comment by LexieCore** [comment]
8.1.2

**Comment by jaydenseric** [comment]
That rules out new ES on old Node as an issue, we're going to need more clues.

Did a previous version work? Are you able to determine which line/position in the source that syntax error throws, or do you mean `function processRequest(request, { uploadDir } = {}) {` is the line?

**Comment by LexieCore** [comment]
When 'apollo-upload-server' is imported this line (inside the module) throws the error:
```sh
 function processRequest(request, { uploadDir } = {}) {
```
The problem seems to be the deconstructing-parameters argument and could also be related to babel.

**Comment by duataud** [comment]
Same problem here. 
It works correctly when I copy-paste it directly the source without installing the module itself. 

Meteor: v1.5
Node: v8.1.2

**Comment by jaydenseric** [comment]
Meteor ships with Node.js v4 (which is crazy old) under the hood. The latest Meteor beta uses a newer version of Node.js that will meet the requirements of this package.

See https://github.com/meteor/meteor/pull/8728.

**Comment by jaydenseric** [comment]
@LexieCore are you using Meteor too?
