### ISSUE TITLE
Support Windows development environment

### ISSUE THREAD

**Issue by tlycken** [jaydenseric/apollo-upload-server#71]
I'm having some issues with testing a server built on this package (see [this](https://stackoverflow.com/questions/49771811/postman-ordering-of-fields-in-form-data-request) and [this](https://github.com/postmanlabs/postman-app-support/issues/4461)) and it ultimately boils down to the fact that [the spec](https://github.com/jaydenseric/graphql-multipart-request-spec#multipart-form-field-structure) requires a specific order of the request body parts, which Postman fails to satisfy.

Since this library can be made less strict about that by simply collecting all parts into a cache before applying the middleware logic, I figured I'd try to submit a PR with that fix, but I can't get the tests to run after a clean clone.

```
$ git clone <this repo>
$ cd apollo-upload-server
$ npm install
...
$ npm run test
...
> apollo-upload-server@5.0.0 postbuild C:\Work\OSS\apollo-upload-server
> prettier 'lib/**/*.{mjs,js}' --write

[error] No matching files. Patterns tried: 'lib/**/*.{mjs,js}' !**/node_modules/** !./node_modules/**
```

If I instead run `npm run watch:test`, all tests fail with the error

```
FetchError {
    code: 'ECONNRESET',
    errno: 'ECONNRESET',
    message: 'request to http://localhost:51517/ failed, reason: read ECONNRESET',
    type: 'system',
}
```

which tells me there's more I have to do to run the tests than just start the test runner in this library.

Is there documentation somewhere on how to contribute, what I need to do to get the development environment up and running etc?

**Comment by jaydenseric** [comment]
Hmm, surprised the development setup didn't work first try. It looks like you are on Windows; perhaps the prettier globs or something else needs to be special to work. A PR to fix Windows support would be welcome!

It is very important logically and for performance for the order of the multipart form fields to follow the spec, so we don't want to allow this. It would be surprising if Postman does not allow ordering of fields; if it really doesn't you might be better off finding a tool that does.
