### ISSUE TITLE
File upload POST request pending

### ISSUE THREAD

**Issue by samholmes** [jaydenseric/apollo-upload-server#75]
I'm facing an issue where the POST request does not get a response from the server. File is uploaded, and the resolvers are called as expected, but the client doesn't get a HTTP response.

**Comment by jaydenseric** [comment]
Are you doing something with the individual file upload streams? They need to be piped into something or the request will never close.

**Comment by samholmes** [comment]
```js
import { requireAuth } from '../../services/auth'
import { createWriteStream } from 'fs'
import constants from '../../config/constants'

export default {
  uploadFile: async (_, { file }, req) => {
    try {
      const { stream, filename } = await file

      await new Promise((resolve, reject) => {
        stream
          .pipe(createWriteStream(constants.UPLOAD_DIR + filename))
          .on('finished', resolve)
          .on('error', reject)
      })

      return true
    } catch (error) {
      throw error
    }
  },
}

```

That's my resolver on the server for the file upload mutation.

**Comment by samholmes** [comment]
I figured out that the event name was incorrect for the WritableStream interface, so I need to replace 'finished' with 'finish' as the appropriate event for when the file has finished being written. This allows the promise to resolve and the resolver async function to finish its invocation.

Further, it should be noted somewhere in documentation that the file stream should be piped in order for the response to be completed. This is a major source of confusion as this isn't obvious behavior. It's expected that if a resolver returns a value, the HTTP response should be sent.

If it's possible, it shouldn't be required that the file stream is consumed at all in order for the HTTP response to be sent. It would make more sense that the stream could be completely discarded if desired. Why must the file stream be consumed?

**Comment by jaydenseric** [comment]
Glad you worked it out!

> It would make more sense that the stream could be completely discarded if desired.

It can, you need to do `stream.resume()`. You can read more about that [here](https://github.com/mscdex/busboy#busboy-special-events).

Node.js streams are really hard to get used too.
