### ISSUE TITLE
Should handle unexpected streaming errors

### ISSUE THREAD

**Issue by koresar** [jaydenseric/apollo-upload-server#77]
The module does not handle unexpected errors happened in the middle of the file streaming. This happens ~4% of the times on 3G networks (last time I checked).

A good example on how to handle them can be found here: https://github.com/expressjs/multer/blob/80ee2f52432cc0c81c93b03c6b0b448af1f626e5/lib/make-middleware.js#L134
```js
        parser.on('error', function (err) {
          pendingWrites.decrement()
          abortWithError(err)
        })
```

Currently, it looks like the module crashes the node.js process. (I do not have proofs of this though.)

**Comment by jaydenseric** [comment]
I have found it very challenging to verify uploads aborted by the client work ok. Some time ago I spent the better part of a week trying to workout a way to reliably test a disconnection and decided it was too difficult. If you or anyone else could work out a way to do so it would be a really big help!

Client aborted uploads have been manually tested (using large files and network throttling in Chrome dev tools) to fail gracefully, although I can't rule out something has changed or was missed.

Errors *must* be listened for on every upload file stream, or they will be uncaught and crash your server. Are you sure that is not the case?

**Comment by koresar** [comment]
I'll see what I can do. Seems doable by mocking the `request` object passed to the `processRequest()` function.

**Comment by jaydenseric** [comment]
Here is an issue for adding tests for client aborted requests: https://github.com/jaydenseric/apollo-upload-server/issues/79.

**Comment by jaydenseric** [comment]
An easy way to cause a crash is to do an upload mutation with a GraphQL error in the query (ask for a field that does not exist or something). The GraphQL server rejects the request as soon as it validates the query, and disconnects before all the uploads resolve causing `FileStreamDisconnectUploadError: Request disconnected during file upload stream parsing.`.

At least thats what happens with [`graphql-api-koa`](https://github.com/jaydenseric/graphql-api-koa) (I don't use Apollo server anymore).
