### ISSUE TITLE
Apollo server v2

### ISSUE THREAD

**Issue by saostad** [jaydenseric/apollo-upload-server#91]
Hi,

Apollo server v2 came out yesterday and they have [File Upload](https://www.apollographql.com/docs/apollo-server/whats-new.html#File-Uploads) enabled by default. 
do you think is there any use case for this package anymore?

**Comment by mike-marcacci** [comment]
[As you can see here](https://github.com/apollographql/apollo-server/blob/496b686240a84d18d3c5a4bc3a3e8f12459e2161/packages/apollo-server-core/package.json#L39) this package is what lets apollo server support file uploads, so it's probably worth keeping around :)

**Comment by saostad** [comment]
Nice!
So because it's now part of Apollo-server-core we don't need to install it separately?

**Comment by mike-marcacci** [comment]
I haven't tried the default settings in Apollo 2.0 (that's on the list for today) but I do believe that's correct!
