### ISSUE TITLE
How to pass `stream.file` to another server as `multipart/form-data`?

### ISSUE THREAD

**Issue by igat64** [jaydenseric/apollo-upload-server#98]
Hi there!

I've started to use `apollo-upload-server` and faced with an issue.
What I want to achieve is to pass (proxy) `stream.file` to another server as a file (`multipart/form-data`). Any ideas how I can do that without saving `files.stream` to the file and then streaming that file to another server?

I've posted similar question [here](https://github.com/form-data/form-data/issues/394)

**Comment by jaydenseric** [comment]
Instead of `stream.file`, did you mean `file.stream`?

I would try using [`node-fetch`](https://www.npmjs.com/package/node-fetch) and [`form-data`](https://www.npmjs.com/package/form-data). Pretty sure you can add the `file.stream` as a file form field, and send the request.

**Comment by igat64** [comment]
> Instead of stream.file, did you mean file.stream?

Yes, I mean `file.stream`.


Also, I was using [`request-promise`](https://github.com/request/request-promise) that under the hood use [`form-data`](https://github.com/form-data/form-data/issues/394), like below

```javascript
import * as request from 'request-promise';
...
async upload(_, { file }) {
  const { stream } = await file;
  return await request.post({
      uri: `${NLP_API_BASE}/upload`,
      formData: {
        datasheet: stream
      }
    });
}
...
```

But I'm getting an error: `RequestError: Error: socket hang up at new RequestError `

**Comment by jaydenseric** [comment]
Maybe check there is no error with the upload in the first place, before trying to setup the forwarding.

Something like:

```js
const { stream } = await upload

await new Promise(resolve => {
  stream
    .on('error', error => {
      console.error('There was an error.')
      reject(error)
    })
    .on('end', () => {
      console.log('There was no error.')
      resolve()
    })
    .resume()
})
```

**Comment by igat64** [comment]
Thank you for the advice!

I've checked this and got `There was no error.` in the console.

**Comment by jaydenseric** [comment]
What is your `upload` resolver meant to return, according to the schema? `return await request.post` doesn't look correct…

**Comment by igat64** [comment]
The resolver should return a `JSON` scalar. Destination server responds JSON.

**Comment by jaydenseric** [comment]
What version of `apollo-upload-server` are you using?

**Comment by igat64** [comment]
Version `6.0.0-alpha.1`

**Comment by igat64** [comment]
This is my current workaround/hack

```js
...
    const tmpFilePath = `${this.config.tmpDirPath}/${uuidv4()}`;
    await new Promise((resolve, reject) => {
      const handlerError = (error) => {
        fs.unlinkSync(tmpFilePath);
        reject(error);
      };
      file.stream
        .on('error', handlerError)
        .pipe(fs.createWriteStream(tmpFilePath))
        .on('error', handlerError)
        .on('finish', resolve);
    });

    const response = await request.post({
      uri: `${this.config.nlpApiBase}/upload`,
      formData: {
        datasheet: fs.createReadStream(tmpFilePath),
        project: botId,
        label: options.label,
      },
      json: true,
    });

    fs.unlink(
      tmpFilePath,
      err => err && console.log('NlpApiService: Failed to delete temporary file', err),
    );
...
```

**Comment by jaydenseric** [comment]
Hmm. I use the current version too, and can pass the `stream` into the [AWS SDK to forward the upload](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property) with no problem.
